version: '3'
services:
  iyp_load:
    image: neo4j/neo4j-admin:5.1.0
    volumes:
      - ./data:/data
      - ./dumps:/dumps
      - ./backups:/backups
    command: neo4j-admin database load neo4j --from-path=/dumps --verbose
  iyp:
    image: neo4j:5.1.0
    container_name: iyp
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
    depends_on:
      - iyp_load
